### ISSUE TITLE
Problem: table of content is redundant in some articles

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/holdex-venture-studio#108]
Problem: This article is way too small and TOC is redundant https://holdex.io/c/companies/clearpool-finance
Solution: make a table of content a component of the thread body (like chart, image, etc.), so we can decide if we want to have it and where we want to have it.

Requested solution
1. Update `api/google-conversion` file to parse Google Document JSON (e.g. https://api.npoint.io/63d3b4aaa5cd23361e65), and return custom element `type: toc`
2. replace the current TOC implementation with the element from the payload

**Comment by georgeciubotaru** [comment]
@salisshuaibu11 Hi, 
Please take your time and analyze first before starting the task

**Comment by salisshuaibu11** [comment]
@georgeciubotaru Ok, I will.

**Comment by zolotokrylin** [comment]
@salisshuaibu11 "Table of Contents"
![image](https://github.com/holdex/holdex-venture-studio/assets/1125014/05da8653-2098-4694-b6ac-76003cf09b52)

**Comment by salisshuaibu11** [comment]
@georgeciubotaru  Oh okay, I need more explanation on this also "Solution: make a table of content a component of the thread body (like chart, image, etc.), so we can decide if we want to have it and where we want to have it.". Where can I find where you used the thread body components to get more insight?

**Comment by georgeciubotaru** [comment]
@salisshuaibu11 If you want to see the code then check `lib/components/BodyRenderer`, if you want visually.
`https://holdex.io` almost every page is generated from a thread

**Comment by salisshuaibu11** [comment]
@georgeciubotaru  Ok, will check it out and let you know if there is anything thank you.

**Comment by salisshuaibu11** [comment]
@zolotokrylin @georgeciubotaru After going through api/google-conversion I stumbled on this function "convertToHoldexJson" Would I need to create another function similar to "convertToHoldexJson" that will parse Google documents or what's the approach I should take?

**Comment by georgeciubotaru** [comment]
Hey @salisshuaibu11  You don't need to create another function, you just need to add handling for `tableOfContents` inside the existing function (same as it's done with `headers`, `body`)

**Comment by zolotokrylin** [comment]
@gigor do you mind claiming this issue?

**Comment by gigor** [comment]
I can, but I am off till Monday

**Comment by gigor** [comment]
@zolotokrylin hi. Do you still want me to do this one?

**Comment by zolotokrylin** [comment]
Yes, after this PR is Problem is resolved: https://github.com/holdex/holdex-venture-studio/pull/393

**Comment by georgeciubotaru** [comment]
@accompany1205  What is the status here?

Missing 3 things.

- Attached PR
- Estimation
- Status of completion

**Comment by surajsharma** [comment]
log: taking this, going to implement the following:

- Update api/google-conversion file to parse Google Document JSON (e.g. [api.npoint.io/63d3b4aaa5cd23361e65](https://api.npoint.io/63d3b4aaa5cd23361e65)), and return custom element type: toc
- replace the current TOC implementation with the element from the payload
- on the frontend, count the number of blocs and if `=<3`, hide the `TOC`

cc @georgeciubotaru

**Comment by zolotokrylin** [comment]
It still appears 
<img width="1015" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/1125014/69c75ea7-950d-487b-b19e-defd5b298aaf">

**Comment by georgeciubotaru** [comment]
@zolotokrylin What closed automatically, issue is not done, the frontend part remains.

@surajsharma You are unblocked to finish it, after you will finish with your current tasks

**Comment by zolotokrylin** [comment]
@accompany1205 Is already working on it I guess.

**Comment by surajsharma** [comment]
@georgeciubotaru ok @accompany1205 can you give some eta on this?

**Comment by georgeciubotaru** [comment]
@zolotokrylin The feature is implemented now in production

To be able to add `TOC` for a specific thread

1. Insert an element in the Google Docs file
![image](https://github.com/holdex/holdex-venture-studio/assets/8217518/f2495115-91df-4c6a-8845-63933dd77dcb)


2. Click on More options
![image](https://github.com/holdex/holdex-venture-studio/assets/8217518/5b5911e1-bee7-41ea-8473-8da006d88fdb)


3. Disable 
![image](https://github.com/holdex/holdex-venture-studio/assets/8217518/87665f2d-df24-4416-b106-d3f9570a8c51)

4. Publish/Save changes
