### ISSUE TITLE
Problem: list is not rendered in table component

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/holdex-venture-studio#225]
> I think these two was 2 separate points on the doc, they seem to be stuck to each other in the online guidelines
<img width="675" alt="Screenshot 2023-05-05 at 1 48 40 PM" src="https://user-images.githubusercontent.com/112711034/236385680-a014afe2-8ef5-47c3-bee5-1197830da389.png">

_Originally posted by @almon-s in https://github.com/holdex/Operations/issues/20

Blocked by: https://github.com/holdex/holdex-venture-studio/issues/309

---

**Comment by georgeciubotaru** [comment]
Log: Problem is available for development

**Comment by accompany1205** [comment]
Hi everyone, I'm working on this.

**Comment by accompany1205** [comment]
@georgeciubotaru how the table should be looked?
Do you have designs?

**Comment by georgeciubotaru** [comment]
@predrag-us Can you help by pointing in designs?

**Comment by predrag-us** [comment]
@accompany1205 The design is attached in the issue description. Please let me know if I can help otherwise. Thank you!

**Comment by accompany1205** [comment]
@georgeciubotaru At this time, the POST method in /google-conversion/api is not being used to parse paragraphs or tables.
Where should the POST method be adapted?

**Comment by accompany1205** [comment]
@georgeciubotaru There is not a parser in /src/lib/components/BodyRenderer/index.svelte.
Should I insert the parser that I did in /google-conversion/api?

**Comment by georgeciubotaru** [comment]
@accompany1205 
1. Update tableBlock parser here: https://github.com/holdex/holdex-venture-studio/blob/main/src/lib/components/BodyParser/index.ts
2. Update table renderer here: https://github.com/holdex/holdex-venture-studio/blob/main/src/lib/components/BodyRenderer/template.pug

**Comment by accompany1205** [comment]
@georgeciubotaru Thanks for your info.
However, I need more details.
To parse data(including paragraphs or tables), I think we need to use POST method that I did in /google-conversion/api, but the parsing script is not being used anywhere.
When I debug the `storeData` [here](https://github.com/holdex/holdex-venture-studio/blob/main/src/routes/(pages)/c/%5Bslug%5D/%5BmessageSlug%5D/%2Bpage.svelte#L24) , the table row data is 
```['List: ItemItemItemItem', '', '']```
I think there isn't an issue [here](https://github.com/holdex/holdex-venture-studio/blob/main/src/lib/components/BodyParser/index.ts) or [here](https://github.com/holdex/holdex-venture-studio/blob/main/src/lib/components/BodyRenderer/template.pug)
What do you think?

**Comment by georgeciubotaru** [comment]
@accompany1205 Good spotting.

I think we need to re-publish the thread to get the changes you have made in the previous PR.
Let me know which threads are you using for test so I can update them.

**Comment by accompany1205** [comment]
@georgeciubotaru what threads do you mean?
I just did `$: console.log({ storeData })` to see the table data at src/routes/(pages)/c/[slug]/[messageSlug]/+page.svelte

**Comment by accompany1205** [comment]
@georgeciubotaru I'm waiting for your response.

**Comment by georgeciubotaru** [comment]
@accompany1205 Here is the thread that contains table elements:

https://holdex.io/c/learn/holdex-hr-guidelines

you can check via localhost `http://localhost:3000/c/learn/holdex-hr-guidelines`

Note: to be able to open the link in localhost, please switch the flag `$lib/config` `previewMock` to true, before pushing revert it back to false

**Comment by accompany1205** [comment]
@georgeciubotaru I can't land on the page
![image](https://github.com/holdex/holdex-venture-studio/assets/96562726/13714bec-40fa-4e83-8b02-6d0df7528670)

**Comment by georgeciubotaru** [comment]
@accompany1205 You can't land because of wrong parsing for tables. Try to comment table block

**Comment by accompany1205** [comment]
> @accompany1205 Good spotting.
> 
> I think we need to re-publish the thread to get the changes you have made in the previous PR. Let me know which threads are you using for test so I can update them.

@georgeciubotaru 
Ah, I see
I tested the table on this page.
![image](https://github.com/holdex/holdex-venture-studio/assets/96562726/caabf2e1-50ca-4190-8434-2b4e87f0db04)

**Comment by georgeciubotaru** [comment]
@accompany1205 Then I will re-publish this thread too.

**Comment by georgeciubotaru** [comment]
@zolotokrylin Please re-publish this thread

**Comment by zolotokrylin** [comment]
log: I have issues with republishing

**Comment by accompany1205** [comment]
@zolotokrylin , @georgeciubotaru did you finish?
We can edit the table content in google docs, can't we?
https://docs.google.com/document/d/1fVHRcyGmEptw7_Rme_XcMvkKklFKyH6ibst4jzf-uvg/edit

**Comment by georgeciubotaru** [comment]
@accompany1205 The thread is re-published
So you have 2 threads that can be tested.

**Comment by accompany1205** [comment]
@georgeciubotaru Do you mean that you've done or still trying?

**Comment by accompany1205** [comment]
@georgeciubotaru I can't see any differences between current and previous [here](https://docs.google.com/document/d/1fVHRcyGmEptw7_Rme_XcMvkKklFKyH6ibst4jzf-uvg/edit)

**Comment by georgeciubotaru** [comment]
@accompany1205 See my comment https://github.com/holdex/holdex-venture-studio/issues/225#issuecomment-1592529368

Also, The Google Docs changes aren't automatically saved, it's required to be published.
I've published the changes and the doc it's using the new API you have created yesterday, not you need to do in-app parser and rendererer

**Comment by accompany1205** [comment]
@zolotokrylin , @georgeciubotaru I addressed this issue.
You can review this [PR](https://github.com/holdex/holdex-venture-studio/pull/396)

**Comment by zolotokrylin** [comment]
@georgeciubotaru check the table rendering here: https://holdex.io/c/learn/principles. Did this PR break it?

**Comment by georgeciubotaru** [comment]
@zolotokrylin If you find other thread, just re-update/re-publish the thread

**Comment by zolotokrylin** [comment]
@georgeciubotaru Yes, I can see other threads and those threads were last time updated months ago.
They are also broke now.. but why? did we also change the renderer logic?

**Comment by georgeciubotaru** [comment]
@zolotokrylin Can you point to one of them? Most of the threads with issue are because of the payload structure

**Comment by accompany1205** [comment]
@zolotokrylin , @georgeciubotaru Could you let me know where you see the break.
I'm happy to help you.

**Comment by georgeciubotaru** [comment]
reference: https://github.com/holdex/holdex-venture-studio/commit/bf13db059253d29d7439331b1739af64004563b7
