### ISSUE TITLE
Problem: Google Conversion API doesn't parse table cell lists

### ISSUE THREAD

**Issue by georgeciubotaru** [holdex/holdex-venture-studio#309]
JSON Document - https://api.npoint.io/c8d0bf6bfd4cdb54328d

Scope:

- update `api/google-conversion` API request to parse the list elements inside table cell

**Comment by power-f-GOD** [comment]
Is anyone working on this still? Or is it fixed?

**Comment by zolotokrylin** [comment]
@power-f-GOD you can claim the issue (assign yourself)

**Comment by zolotokrylin** [comment]
Actually, I realized you already have an issue in progress (https://github.com/holdex/holdex-venture-studio/issues/353). We have `WIP limit = 1`.

**Comment by power-f-GOD** [comment]
HI, @zolotokrylin . I finished #353 locally, but I'm neither able to push remotely nor create a PR yet due to permission issues/restrictions.

So, is it "legal" to take on this task now, or wait till after I make a PR for the aforementioned? What do you propose?

**Comment by zolotokrylin** [comment]
go for it @power-f-GOD

**Comment by zolotokrylin** [comment]
@georgeciubotaru he can't assign himself becasuse of the same limitation as creating PRs if you are not a member or collaborator. For now we assign people (maintain issues)

**Comment by accompany1205** [comment]
I think this issue is being identified here.
![image](https://github.com/holdex/holdex-venture-studio/assets/96562726/e4fcf1b0-6674-485b-bec8-619dbc36fa6f)
Could you show me the designs of how the table should look?

**Comment by accompany1205** [comment]
At this time, it seems that POST function in /routes/api/google-conversion/+server.ts is not being used for conversion of tables(Google docs - https://docs.google.com/document/d/1fVHRcyGmEptw7_Rme_XcMvkKklFKyH6ibst4jzf-uvg/edit)
Could you let me know which function(where) we're using for the conversion?

**Comment by accompany1205** [comment]
I tested current script of `api/google-conversion` with JSON input on Postman, but it failed with error "Cross-site POST form submissions are forbidden"
Do I need to give correct access?
![image](https://github.com/holdex/holdex-venture-studio/assets/96562726/e9c9b95f-755a-4ee2-8a83-e39ce2908608)

**Comment by accompany1205** [comment]
@georgeciubotaru could you help me with above comment?

**Comment by georgeciubotaru** [comment]
@accompany1205 
1. I cannot see the JSON data pasted in the body
2. You are using `Text` as the content of the element instead of `JSON`

![image](https://github.com/holdex/holdex-venture-studio/assets/8217518/b8c2dbe3-4571-4bee-bd45-72bd56884519)

**Comment by accompany1205** [comment]
@georgeciubotaru thanks for you help.
I'm copying entire data of https://api.npoint.io/c8d0bf6bfd4cdb54328d. Am I right?

**Comment by georgeciubotaru** [comment]
@accompany1205 Yes

**Comment by power-f-GOD** [comment]
> go for it @power-f-GOD

Going for it.🚀😎

> Also, this task have already a PR, you can use it as a starting point.

Ok.📝 Can you mention me on the PR in particular?

**Comment by accompany1205** [comment]
> Updated as following. PR #316 raised
> 
> ```
>  [
>             {
>               "type": "list",
>               "data": {
>                 "items": "Hire.Reject"
>               }
>             },
>             {
>               "type": "paragraph",
>               "data": {
>                 "text": "customer"
>               }
>             },
>             {
>               "type": "paragraph",
>               "data": {
>                 "text": "Pandadoc"
>               }
>             }
>           ]
> ```

@georgeciubotaru  how should the response look like?
Could you show me sample response?

**Comment by georgeciubotaru** [comment]
@accompany1205 The result is correct, but the implementation is not.

**Comment by georgeciubotaru** [comment]
![image](https://github.com/holdex/holdex-venture-studio/assets/8217518/2096ea36-499e-4eeb-b4de-1624fefdca28)

@accompany1205 What if the payload will contain
1. paragraph
2. list
3. paragraph

Or just 
1. list
2. list
3. list

Or
1. quote
2. list
3. p with inline elements

**Comment by georgeciubotaru** [comment]
@accompany1205 Yep

**Comment by accompany1205** [comment]
@zolotokrylin @georgeciubotaru  I fixed this issue.
Could you give me permission for this repo so that I could create a PR?

**Comment by power-f-GOD** [comment]
@accompany1205 , you'd have to fork the repository (instead of cloning) and push your changes to your `forkedRepo` and then make a PR from the same.📝
