### ISSUE TITLE
Problem: there's no new design for tweet skeleton

### ISSUE THREAD

**Issue by georgeciubotaru** [holdex/holdex-venture-studio#324]
@zolotokrylin @georgeciubotaru there's no new design for tweet skeleton?

_Originally posted by @surajsharma in https://github.com/holdex/holdex-venture-studio/issues/60#issuecomment-1562551454_
            
# [Figma design](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/UI-Design?type=design&node-id=2739-39127&t=HgOpUFc7qEuWAZsi-4)

**Comment by georgeciubotaru** [comment]
@surajsharma How about to finish the this task until you will receive access to Clearpool Vercel?

**Comment by surajsharma** [comment]
@predrag-us 

> We have a general example (+ note) of how the skeleton is looking like & being built ⏤ [URL](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/UI-Design?type=design&node-id=943%3A8239&t=maB828ut5QJQrZu5-1).

i don't see a skeleton example or note here, just fully rendered components


> When preparing a skeleton for a new component ⏤ replace the target element(s) with a rectangle having the same styles as in the example above.


unclear which styles are being referred to, pls elaborate

**Comment by georgeciubotaru** [comment]
@surajsharma See via the link from comment (3rd frame from the left)
I cannot write you a comment because cannot mention you

**Comment by georgeciubotaru** [comment]
@surajsharma What is the status here?

- Please attach the PR
- Leave an estimation (in the PR description)

**Comment by surajsharma** [comment]
@georgeciubotaru pr up

**Comment by markholdex** [comment]
> @georgeciubotaru this is proving difficult without the actual design, attaching a PR with estimate momentarily

@surajsharma the design of the skeleton was attached in previous comments. Here is the link: https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/UI-Design?type=design&node-id=2739-39127&t=HgOpUFc7qEuWAZsi-4

i've also added it to description. 

cc @predrag-us
