### ISSUE TITLE
Problem: Lupan Roman's first problem statement for Holdex!

### ISSUE THREAD

**Issue by LupanRoman** [holdex/holdex-venture-studio#339]
# Problem statement
Hello,
I am Roman, a Front-end developer. I like to take on problems and come up with solutions for those problems. Solving problems and providing a product that clients can enjoy is my primary goal. I am a responsible and well-organized person, who knows how to get things done and how to achieve every goal. There is no such thing a problem without a solution.
I am very happy to learn from the best and also contribute to the future products for Web3.

**Comment by zolotokrylin** [comment]
Hi @LupanRoman ,
Thank you for your introduction and welcome to try our trial tasks! 

You can take this one as your first task: https://github.com/holdex/holdex-venture-studio/issues/291
