### ISSUE TITLE
Subscribe CTA ⏤ Subscribed State

### ISSUE THREAD

**Issue by predrag-us** [holdex/holdex-venture-studio#34]
**Design**
Preview: [URL](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/UI-Design?node-id=1310%3A9403&t=QXADdSEEj6WqsUlG-1)
Components: [URL](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/UI-Design?node-id=782%3A8158&t=QXADdSEEj6WqsUlG-1) 
Destructive Button Component: [URL](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/UI-Design?node-id=256%3A189&t=QXADdSEEj6WqsUlG-1)

**Comment by zolotokrylin** [comment]
It is already being handled here:
- https://github.com/holdex/holdex-venture-studio/issues/372
- https://github.com/holdex/holdex-venture-studio/pull/453

Sorry, this issue is a duplicate.
