### ISSUE TITLE
Problem: links are not rendered inside the quote element

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/holdex-venture-studio#340]
Problem
Links are not rendered inside the quote element. Example of the article with this problem: https://holdex.io/c/learn/editorial-guidelines

<img width="929" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/1125014/9a52508c-0023-4aba-aa98-85699bd7057f">

### [JSON output](https://api.npoint.io/b2d9cd937c3eec83fc0b)

**Comment by LupanRoman** [comment]
Can you please describe the problem with more details.

**Comment by surajsharma** [comment]
@LupanRoman 

The following files should give you a clue

https://github.com/holdex/holdex-venture-studio/blob/main/src/lib/components/BodyRenderer/inline.svelte


https://github.com/holdex/holdex-venture-studio/blob/main/src/lib/components/BodyRenderer/Blocks/link.svelte

**Comment by surajsharma** [comment]
@LupanRoman if you are still working on this could you assign the issue to yourself?

**Comment by LupanRoman** [comment]
@surajsharma Sure.

**Comment by zolotokrylin** [comment]
@LupanRoman please attach the PR to this issue. Aim to commit frequently into your branch, so we can see the progress.

> Limit and scope your work to smaller deliverables (PRs). Aim to deliver something every 3-4 hours.

This quote is from our [guidelines](https://holdex.io/c/learn/github-strategy).

**Comment by georgeciubotaru** [comment]
@jewelas You can take this task.
Please first analyze.

**Comment by jewelas** [comment]
I got it. @georgeciubotaru 
Thank you.

**Comment by jewelas** [comment]
![vmplayer_SYjEdnTiS2](https://github.com/holdex/holdex-venture-studio/assets/121175573/e6c4f3ea-bfbd-4266-95ab-4d285119a4ef)
Is this issue already solved? @georgeciubotaru @markholdex 
Because I see the links are rendered inside the quote elements.

**Comment by jewelas** [comment]
I just tried to render the paragraph inside the quote element and see the above image.

**Comment by zolotokrylin** [comment]
@jewelas what's your PR? please attach it here

**Comment by jewelas** [comment]
[PR Link](https://github.com/holdex/holdex-venture-studio/pull/380)
This is my working branch and I replaced the paragraph case with the quote case.
And you can see the links are rendered inside the quotes.
@zolotokrylin

**Comment by jewelas** [comment]
so I think this can be closed since it already worked on the main branch. @zolotokrylin 
Can you assign me another task please? Or should I pick up anyone else?

**Comment by markholdex** [comment]
@jewelas hey, you are right, links seems to work within the blockquote however, there is an issue when I try to make the following paragraph into a qu
<img width="994" alt="Screenshot 2023-06-14 at 18 25 05" src="https://github.com/holdex/holdex-venture-studio/assets/46079535/2c39413c-632e-4901-ac84-547243264e44">
ote. 

The result is the same from the screenshot in the Problem description. I thought maybe 2 links are not supported so I removed the second one, the problem is the same however. 

These articles are deployed through a custom plugin that we created for Google Docs. Our parser (from the current repo) is the one responsible for the output, as the rendered seems to work fine. You can find our parse in the api/googleconversion folder of the project. I will provide you with the JSON output the parser returns for the current problem.

**Comment by markholdex** [comment]
@jewelas here you go. This is the output our parser receives when I try to make that paragraph into a quote: https://api.npoint.io/b2d9cd937c3eec83fc0b

**Comment by jewelas** [comment]
Thanks for your info.
Btw, can I see that article while running localhost?
Because I don't see anything at http://localhost/c/learn/github-strategy

**Comment by markholdex** [comment]
@jewelas The article is not available on localhost. Our localhost runs the stage environment by default. You can switch it to run the production environment as you test things out and then switch back to staging. You can do this in the lib/config file by settings the value to true. 

![image](https://github.com/holdex/holdex-venture-studio/assets/46079535/4ada6665-6075-4923-8f59-5e807dccb07b)

**Comment by zolotokrylin** [comment]
@markholdex Another option is to have the same article in stage, or an article which has all types of text content (inline and block elements) which will serve as a testing article

**Comment by jewelas** [comment]
> 

set it as true take me to this page.
![vmplayer_JtS9aVllTH](https://github.com/holdex/holdex-venture-studio/assets/121175573/da5352c3-cafb-46d5-9f93-8b701ae16105)

**Comment by georgeciubotaru** [comment]
@jewelas You are checking this URL
`http://localhost:3000/c/learn/github-strategy`

**Comment by georgeciubotaru** [comment]
@jewelas Check the URL I've sent

**Comment by jewelas** [comment]
![image](https://github.com/holdex/holdex-venture-studio/assets/121175573/70cd52c2-c3e7-4179-9af5-bba61b60bd31)
It works well locally, plz have a check again on the main branch.
Or plz lmk how I can reproduce this issue. @georgeciubotaru @markholdex

**Comment by markholdex** [comment]
@jewelas I believe the problem is not in the renderer. I believe you are testing things by transforming the paragraph into quote manually. But the way our Article works is that our parsers are going to transform these paragraphs into quote automatically. 

The initial parser is in the `api/google-conversion`. It parses the JSON I attached in the description previously. After parsing, it transfer the output to our `renderer` parser. So it might be an issue somewhere there because the automatization process doesn't behave the same as you would if you change things manually.

**Comment by markholdex** [comment]
I updated the article link in the description with an article that has this problem. This is the quote that should include the link but doesn't
<img width="768" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/46079535/259fd087-5696-4761-a4ed-c75bc3ef1f91">

**Comment by markholdex** [comment]
@jewelas FYI

**Comment by jewelas** [comment]
I'm still investigating on this issue.
It might need a few hours more.
I'll try to deliver it tomorrow morning.

**Comment by georgeciubotaru** [comment]
@jewelas What is the status here?

**Comment by surajsharma** [comment]
why is this still open? @jewelas

**Comment by jewelas** [comment]
I'm waiting for the reply from the team.

**Comment by markholdex** [comment]
hey @jewelas we were waiting for your results that you promised. We are not able to give you a proper evaluation without seeing the result. When can we expect to be delivered? 

> I'm still investigating on this issue. It might need a few hours more. I'll try to deliver it tomorrow morning.

**Comment by jewelas** [comment]
![image](https://github.com/holdex/holdex-venture-studio/assets/121175573/dd58dc64-5326-40c8-9fa7-ae12a92966fb)
Hey @markholdex .
Where I can find this quote? Or link for this?

**Comment by predrag-us** [comment]
@jewelas Please check the description.

> I updated the article link in the description with an article that has this problem.

**Comment by jewelas** [comment]
I can't get link data in the renderer parser. I think there is a problem in the parser in google-conversion.

**Comment by jewelas** [comment]
Can I test the parser in google-conversion?

**Comment by georgeciubotaru** [comment]
@jewelas Yes, You can fork the repo, start the development server and test the API via Postman

1. 
`http://localhost:300/api/google-conversion`
```
body: {
	data: <PUT_JSON_HERE>
}
```

**Comment by jewelas** [comment]
could you send me an example for testing the parser?

**Comment by jewelas** [comment]
I need to know the form of data to submit. @markholdex

**Comment by jewelas** [comment]
@markholdex 
I can't find quote in the data.
I need outputs which includes quote data.
Plz send me another example includes quote.

![image](https://github.com/holdex/holdex-venture-studio/assets/121175573/4a74b2e7-93c1-4f6d-a14e-817601a08572)

**Comment by georgeciubotaru** [comment]
@georgeciubotaru The JSON from the endpoint doesn't know about the `quotes` and other elements.

Paragraphs with the`>` prefix will be parsed by the API I've mentioned and will return in the output the `quote` elements
