### ISSUE TITLE
Problem: Problem: "@mention" is not displaying correctly in the published article

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/holdex-venture-studio#342]
> The "@mention" is not displaying correctly in the published article for me <img width="622" alt="Screenshot 2023-06-06 at 1 04 03 PM" src="https://github.com/holdex/operations/assets/112711034/6116042e-2cc2-422a-ba94-159b9615415a"> 
Google Doc
<img width="589" alt="Screenshot 2023-06-06 at 1 03 46 PM" src="https://github.com/holdex/operations/assets/112711034/7e83f5bb-be06-4595-a5d2-54e3e2291720">

_Originally posted by @almon-s in https://github.com/holdex/operations/issues/17#issuecomment-1577912659_

**Comment by surajsharma** [comment]
@zolotokrylin  the images you linked to are broken

**Comment by almon-s** [comment]
This is solved now. Will be closing
