### ISSUE TITLE
Gheorghi's first problem statement for Holdex!

### ISSUE THREAD

**Issue by SweetBubalehj** [holdex/holdex-venture-studio#343]
**Greetings Holdex team!**
My name in Gheorghi but from childhood I am called Egor, I am from **Chisinau, Moldova**!
IT and blockchain enthusiast, I believe in blockchain technology and cryptocurrency, dealing with tokens, nft's, airdrops, sometimes retrodrops. My main stack is **Solidity + Node**.

It is my trial week for now, but after a week I hope to be a part **Holdex team**!

**Comment by zolotokrylin** [comment]
Hi Egor,
Welcome to your trial week. 
@georgeciubotaru will provide you with your first smart contracts assignment.

**Comment by SweetBubalehj** [comment]
@georgeciubotaru can I know when I can start my assignment?

**Comment by georgeciubotaru** [comment]
Hi Egor, nice to meet you!

I'm preparing for you a suitable task:
https://github.com/holdex/holdex-venture-studio/issues/309

Let me know if you encounter any issue, also take your time to analyze the Problem

**Comment by SweetBubalehj** [comment]
@georgeciubotaru 
Should I wait and expect smart contracts assignment or you just give me issue #309 ?

**Comment by georgeciubotaru** [comment]
@SweetBubalehj The provided issue is for you

**Comment by SweetBubalehj** [comment]
Again hello. I have tons of questions and issues with this assignment. 

1. There's not enough details about the work, I tried to understand details by viewing old member questions and commits - Mayur Borse but I can't clearly understand what should I do.
2. Issues with code review experience - everything I see is just uncommented parser. No info where it is called from, how should I use it, how should I test it, how and why it should be updated.
3. Wrong job expectations - by applying job as a Full Stack web3 developer I thought I would be dealing with smart contracts and their integration.

I didn't expect to see my trial week like that.

**Comment by markholdex** [comment]
Hey Egor, nice to meet you.

1. By looking at the #309 description you can see that the scope is to update the API request to parses the list of elements inside the `table cell element`. The JSON that contains this `table cell element` is the one to be parsed and is also presented in the description. 
2. Current script is outdated and doesn't parse `table cells` (as states in the Problem definition). The location of the script is in the `api/google-conversion` folder of the current project.
3. As you applied to our Full Stack Web3 position, during the trial period, we will test various skills of yours. Full Stack role expects you to handle various tasks. Starting off with basic java-script and following with your ability to make task assessments or figuring out smart-contract solution in the context of business goals.

Let me know if I didn't answer your questions. Looking forward to your results!

**Comment by SweetBubalehj** [comment]
Alright, script is in **api/google-conversion** but where elements should be parsed to? **/c/jobs/scrum-master** doesn't seen to be right. This project is new for me and have troubles with hierarchy and location, sorry.

**Comment by georgeciubotaru** [comment]
Hey @SweetBubalehj,

Let's clarify the scope of this task.

You need to update the `api/google-conversion` file, so that when a request comes with the input (see the JSON provided), the request will parse it and return the expected response. (you can try via POSTMAN to do the request).

Regarding the UI, there it's a separate task for that.

Let me know if you have any questions.
