### ISSUE TITLE
Problem: Clearpool Prime User Guide has console error 403

### ISSUE THREAD

**Issue by TerrenceAddison** [holdex/holdex-venture-studio#344]
# Problem statement

- [ ] When opening the url https://holdex.io/c/learn/clearpool-prime-user-guide, notice in console there are multiple 403 errors:
![image](https://github.com/holdex/holdex-venture-studio/assets/63777677/2d9a8b32-8b68-4a5c-b931-819654e207ee)

This also happens when clicking some items under the TOC including Dashboard, Liquidity, Callback, My Positions etc.

**Comment by zolotokrylin** [comment]
It is an issue with the images. Images are not accessible.
We will solve it together with #115
