### ISSUE TITLE
Invalid response from route /api/tweets: handler should return a Response object

### ISSUE THREAD

**Issue by markholdex** [holdex/holdex-venture-studio#349]
View details in Rollbar: [https://rollbar.com/holdex/Holdex/items/4431/](https://rollbar.com/holdex/Holdex/items/4431/)

```
Invalid response from route /api/tweets: handler should return a Response object
```

**Comment by zolotokrylin** [comment]
caused by #313

**Comment by georgeciubotaru** [comment]
@zolotokrylin `api/tweets` it's not used anymore, we can `backlog` this issue

**Comment by zolotokrylin** [comment]
@georgeciubotaru you mean we can close it (or delete it)?

**Comment by georgeciubotaru** [comment]
@zolotokrylin better to close it
