### ISSUE TITLE
Problem: Humongous linter errors and warnings (with squiggly lines)

### ISSUE THREAD

**Issue by power-f-GOD** [holdex/holdex-venture-studio#353]
# Problem statement

There are lots of eslint errors and warnings which are mostly caused by leaving unused variables (lying around) or using TS `any` (which should be discouraged and only used where necessary) or using undefined variables or defining variables with `let` (instead of with `const`) when they never will be re-assigned etc.

# Proposed solution

- [x] Update the eslint `lint` script in `package.json` (and run the same) to fix all fixable warnings/errors
- [x] Turn off the `no-explicit-any` rule (temporarily) by ts-eslint
- [x] Add eslint "fix all on save" setting in `.vscode/settings`
- [x] The first two bullets above only partially reduce the warnings/errors meanwhile the rest errors/warnings would need human/manual intervention e.g. commenting out unused or undefined vars
- [x] Extra: Add a few more rules to enforce some coding conventions and standards

### ETA

- [x] First three bullets would take less than 0.5 hours while the third may take around 3-4 hours (or more) to complete depending on the size of the project which I cannot exactly ascertain yet.

<img width="882" alt="Screenshot 2023-06-10 at 12 44 36 AM" src="https://github.com/holdex/holdex-venture-studio/assets/28790485/d3f89333-d953-454e-9372-11f7bf628f52">

**Comment by power-f-GOD** [comment]
@zolotokrylin , could you please assign this problem to me and add the relevant labels? Thank you. 🤲🏼

**Comment by power-f-GOD** [comment]
Hi, @zolotokrylin .

Kindly, can you grant me permission to push? I'm getting the below error currently:

```zsh
remote: Permission to holdex/holdex-venture-studio.git denied to power-f-GOD.
fatal: unable to access 'https://github.com/holdex/holdex-venture-studio.git/': The requested URL returned error: 403
```

Gracias.🤲🏼

**Comment by power-f-GOD** [comment]
Okay, I made an observation. While going through the files, I noticed that some variables that are not used within the `.svelte` files are actually used within the referenced `.pug` files. I apologize, as I'm new to `pug`.🤲🏼🥲

And during my investigation into why Visual Studio Code wasn't greying out the unused variables in the `.svelte` files (as it normally does), I decided to experiment by commenting out a `template` element, and voila! The unused variables became greyed out. This led me to examine the `.pug` files and I discovered that the unused variables were used or embedded within strings. Quite interesting!

@georgeciubotaru , please feel free to correct me if I have misunderstood anything.🤲🏼 And also, could you please explain why we're using `.pug`? Again, I apologize as I'm new to `pug`.🤲🏼

PS. As a result of my discovery, I may need to disable eslint completely in certain `.svelte` files since it will be difficult for me to determine which variables are used and which ones are unused just by examining the files.💔

**Comment by power-f-GOD** [comment]
<img width="670" alt="Screenshot 2023-06-11 at 12 30 11 AM" src="https://github.com/holdex/holdex-venture-studio/assets/28790485/d799df79-57f9-469a-b671-ec52a3e72825">
89fdb-dca8-4c6b-aae8-848c7b2dd395">

<img width="569" alt="Screenshot 2023-06-11 at 12 24 08 AM" src="https://github.com/holdex/holdex-venture-studio/assets/28790485/d94fa0dd-aa56-415c-8bf5-fdd60c2dffc1">

@georgeciubotaru , the `src` attribute on the `template` element doesn't seem to be valid, hence the red squiggly line. Kindly, how did you implement it? 

And even after trying to augment its interface [`HTMLTemplateElement`], one drawback of Svelte I long found out is that TypeScript is of non-effect in its `JSX` land.🥲

**Comment by power-f-GOD** [comment]
<img width="787" alt="Screenshot 2023-06-11 at 2 57 43 AM" src="https://github.com/holdex/holdex-venture-studio/assets/28790485/54051ed9-89c4-4127-8ba4-13c9889de90b">

`eslint` errors and warnings annihilated!✅

**Comment by zolotokrylin** [comment]
@power-f-GOD sounds good! 
You need to use forking feature to create your pool request: https://docs.github.com/en/get-started/quickstart/fork-a-repo#propose-changes-to-someone-elses-project

**Comment by georgeciubotaru** [comment]
Hi @power-f-GOD thank you for reporting this problem.

1. We are using a `.pug` file to keep DRY and cleaner code, also we minimize the HTML lines needed to write in order to develop a complex component. Also, we are trying to avoid errors when `<` can be forgotten which can break the functionality, but is not discoverable by `lints`
2. Regarding importing `.pug` file using `<template src/>` this error is related to the VSCode plugin so ignore it for now.

I'm open to other solutions that will help us to quickly write/read component code and debug it easier.

**Comment by power-f-GOD** [comment]
@zolotokrylin , All right. Noted. Will do. ✅

@georgeciubotaru , thanks for your response.

Ok. For...

1. Yeah, correct! I'm (also) an advocate of DRY and clean code.🙌🏼❤️ However, for the three concerns raised, 
    - for the first, "DRY code": I think creating reusable Svelte components (and features) solves this, IMO;
    - for the second, "minimize HTML lines": I think the number of HTML lines when eventually compared with its pug counterpart would be negligible or insignificant;
    - for the third, "avoid errors when `<` can be forgotten": I think this would no longer be a problem moving forward. In the PR which I will create in a moment on the context problem, I enabled `eslint` in the editor (`.vscode`) settings, so the editor will always discover when a tag is not closed.✅
    
2. All right.📝 Already ignored.✔ Although, the squiggly lines persist. But I just wanted to know if, in your implementation, it is possible to use `data-src` rather than `src`.

> I'm open to other solutions that will help us to quickly write/read component code and debug it easier.
Yeah, thanks for this line. I'm also open to learning new things that make me better (and more efficient) at what I do.

So, in the case of using `.pug`...Ok, make no mistakes, I'm not about to say we rewrite everything `.pug` using the reusable Svelte components approach, however, we can adopt it moving forward. But a few things [cons/problems] I've observed by just going through the `.pug` files are these:

1. Error discovery: Because a lot of the logic (and functions or variables) are hidden within strings, it is hard to see errors and this leads to number 2...
2. Debugging and maintainability: Due to the above, debugging becomes harder, and maintainability also as a result;
3. Editor features/support: Linting in the `.pug` is (almost) inexistent. Also, auto-completion, syntax highlighting, (and IntelliSense) as well (which is one reason I had to disable a particular `eslint` rule in all files that reference a `.pug` file). These make it harder to do "1" and "2" above or enforce any form of code quality standards (or conventions).
4. Readability/Collaboration: This is based on what I experienced going through the `.pug` files (and it may not be the same for every other developer), but the syntax is less intuitive and less explicit compared to general HTML/markup, hence slow down (or impede) collaboration.

These are my positions on the matter and may need to be considered in the future.🤲🏼

Thank you.🙇🏽‍♂️

I'll proceed to create a PR (in a moment) on the context problem.🚀

**Comment by power-f-GOD** [comment]
Ok. So, I was just about going through [review] my code as I am creating a PR, and I noticed the indentation is extreme (8 chars/spaces long😶‍🌫️). Ideally, should be two spaces long (based on Google's standard).🤲🏼 8 chars make it sparse and harder to scan from left to right😓, but 2 spaces make it more compact and easier to scan through.✅ (Note that you may not notice this in your editor).

<img width="1212" alt="Screenshot 2023-06-12 at 3 01 54 PM" src="https://github.com/holdex/holdex-venture-studio/assets/28790485/f09d5a0e-7305-47cf-bbb2-58406e63846a">

Hence, permit me to update these lines in the `.prettierrc` file and add the same to the`.vscode/settings.json` file:

Before:
```
        ...
        "useTabs": true,
	"tabWidth": 2,
        ...
```

After:
```
  ...
  "useTabs": false,
  "tabWidth": 2,
  ...
```

What do you all reckon?

Cc: @zolotokrylin , @georgeciubotaru , @markholdex

**Comment by zolotokrylin** [comment]
Don't bloat the problem scope @power-f-GOD.
You can log it as a separate problem if it doesn't exist already (check it before creating a new issue).

**Comment by power-f-GOD** [comment]
All right, @zolotokrylin . Noted.📝 I'll log it under any existing problem with *formatting*. That works?

**Comment by power-f-GOD** [comment]
Hi, @zolotokrylin , @georgeciubotaru  . Kindly, I made a PR for the context problem here: [PR #368 - Solution to #353](https://github.com/holdex/holdex-venture-studio/pull/368) . ✅

Do review, drop your feedback, and, ultimately, merge accordingly.🙌🏼

I'll proceed now to the other task.🏃🏽‍♂️
