### ISSUE TITLE
Problem: crypto price tickers don't display current price inside the articles

### ISSUE THREAD

**Issue by markholdex** [holdex/holdex-venture-studio#374]
# [Figma design](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/UI-Design?type=design&node-id=358-2334&t=RjsAo7h4yifRb5Cj-4)

# Problem
Our articles contain different cryptocurrency tickers in their content like $ETH  or $BTC. They are highlighted already but the users have to visit 3rd party websites to view current price while reading an article.

# Solution
- [ ] By hovering a price ticker, display the current USD price
- [ ] Display an empty state for tickers that don't have a price yet
- [ ] Make sure `$100` or similar text that includes value are not affected

Example article: https://holdex.io/c/learn/understanding-pickle-a-beginners-guide-and-review

**Comment by gigor** [comment]
Hey there, I'd like to work on this issue if it's not yet complete.

**Comment by gigor** [comment]
@zolotokrylin Great, thanks. Can you advise on how to create articles locally or if there is a way to switch to prod db for read-only?

**Comment by markholdex** [comment]
hey @gigor sorry for not being explicit yet. I can point you to the [follow comment ](https://github.com/holdex/holdex-venture-studio/issues/340#issuecomment-1591638091)that can help you.

**Comment by gigor** [comment]
Hello again. So far, I have done the visual stuff and main logic, but I am a bit lost on how your APIs work and how to query data for specific coins.

Here is the WIP pull request: https://github.com/holdex/holdex-venture-studio/pull/393

In theory, I can make 2 requests per ticker to Coingecko, but maybe you already have a service somewhere?

**Comment by markholdex** [comment]
@gigor good question. In `api` folder we have `marketinfo` request that we use to generate the prices for fancy charts on the home page and inside other articles. We also use coingecko for the prices.
You can have a look at the request and make a separate endpoint for the price ticker. Once completed and works good, you can cache the request for 15 min so we don't exceed the rate limit. Let me know if it helps.

**Comment by gigor** [comment]
@markholdex, thanks. So I am gonna do 2 consecutive queries:
1. https://www.coingecko.com/en/search?query=btc to resolve coin id from ticker symbol
2 https://www.coingecko.com/en/coins/bitcoin to get actual data

Is it an acceptable solution, or is there a better API somewhere?

**Comment by markholdex** [comment]
@gigor I think you can just do it in a single request. Because you already know the ticker symbol from the Article body, and you can pass this ticker symbol into the API request. Check our `market-info` example from `api` folder. We did 2 requests there to get the chart too but you don't need the chart as you can see.

**Comment by gigor** [comment]
@markholdex I've seen the code, and `https://www.coingecko.com/en/coins/{tickerCode}` results in 404, same as if you try `https://api.coingecko.com/api/v3/coins/btc` 

Does `{utilsApiUrl}/market-data/coins` accepts parameters other than `url` & `source`? Are there docs on the API somewhere?

**Comment by markholdex** [comment]
@gigor in this case I would suggest to check their official docs on their website.

**Comment by gigor** [comment]
Is `https://stage.tools.holdex.io/api/market-data/coins` just a proxy to Coingecko API, or is there more to it? Does it have documentation?

**Comment by gigor** [comment]
Updated pull request. Please review. 
All in, it took around 8hrs.
