### ISSUE TITLE
Problem: Extreme code indentation in code review screens

### ISSUE THREAD

**Issue by power-f-GOD** [holdex/holdex-venture-studio#375]
# Problem statement

- [ ] See [here for problem statement](https://github.com/holdex/holdex-venture-studio/issues/353#issuecomment-1587440043)

# Proposed solution

- [ ] See [the same for solution(s)](https://github.com/holdex/holdex-venture-studio/issues/353#issuecomment-1587440043).
- [ ] Re-format all files in the project/repo after the update.

### ETA

- [ ] 0.5hrs.

**Comment by power-f-GOD** [comment]
Will solve this as soon as #381 gets merged. 🤲🏼

**Comment by power-f-GOD** [comment]
In coding...👩🏽‍💻⏳

**Comment by power-f-GOD** [comment]
Done.✅ Will make a PR as soon as #381 gets merged. 🤲🏼

Moving on to my final problem for the **7-day trial**: #386 . 🏃🏽‍♂️🚀

**Comment by power-f-GOD** [comment]
Ok. Had to hold on with #386 and return to this as I noticed that the `.pug` files weren't formatted by `prettier`, so I had to make some investigation and install its [plugin](https://prettier.github.io/plugin-pug/guide/), configured the same (to prevent errors that arose), and re-ran the `format` script to format all `.pug` files and `.svelte` files (that had `pug` in them).✔️

Will proceed now to the paused problem.🏃🏽‍♂️

**Comment by zolotokrylin** [comment]
@power-f-GOD Good job!
