### ISSUE TITLE
Problem: website visitors are not aware of our services

### ISSUE THREAD

**Issue by predrag-us** [holdex/holdex-venture-studio#379]
Problem: Website visitors aren't aware of our services.
Solution: Create a dedicated `/services` page explaining what're the services that we're offering.

--- 

```[tasklist]
### To Do
- [x] Write the copy
- [x] add relevant hashtags (view list of suggested hashtags in Editor Guidelines article)
- [x] publish article in most relevant category
- [x] add links to this article from `/` and `/about` article bodies and re-publish that articles
```

---

**Comment by predrag-us** [comment]
- We don't have the luxury of adding `/services` in the Navigation since there's no available space. Adding `/services` to the Navigation would require the Navigation redesign. Therefore, I would recommend keeping `/services` as a CTA on `/`. 
- We need to prepare the copy for the `/services` CTA on `/`. 
- We need to prepare the copy for `/services`.

@markcurchin Please let me know do you agree and if you think I'm missing something. Thank you!

**Comment by zolotokrylin** [comment]
What's the copy for the services? We need a google doc article please

**Comment by predrag-us** [comment]
@zolotokrylin @markcurchin 

The first draft is attached.

**Comment by zolotokrylin** [comment]
@predrag-us I have requested access to the doc. Please provide edit permissions, so I can move it into our common Drive from which we can publish the doc on our site later on. Thanks

**Comment by zolotokrylin** [comment]
@almon-s what do you think? Do you have suggestion regarding the copy?

**Comment by almon-s** [comment]
@zolotokrylin copy looks good to me, besides the ToC. We may not even need it since it's not as lengthy. Just suggested some subheadings on the doc

@predrag-us will this go under the "How do we contribute?" on `/` as CTA? and are the service subheadings on the figma design just placeholders or do they also need to be included on the doc?

**Comment by predrag-us** [comment]
@almon-s That's right, I was thinking of having a CTA under the `How do we contribute?`. The design is a placeholder prepared prior to writing the copy. I should replace the content with the one from the doc.  

Also, I'm missing the intro. I'll ping you to check once I have it ready.

**Comment by predrag-us** [comment]
@almon-s Intro is ready. Please check. Thank you!

**Comment by zolotokrylin** [comment]
I have updated the checklist in description, please check @predrag-us

**Comment by almon-s** [comment]
@predrag-us the content looks good, added the hashtags. Do you plan on editing the `/` article aswell? Or after this has been published?

**Comment by markholdex** [comment]
Guys, I think we are also missing the CTA component in the renderer. Means there's no way to add a CTA section/component to a doc. I will create relevant problem

**Comment by markholdex** [comment]
Updated the checklist description and added the new task

**Comment by zolotokrylin** [comment]
> .. missing the CTA component in the renderer. This means there's no way to add a CTA section/component to a doc. I will create relevant problem

Guys, let's not make the #390 as a blocking issue here. There are other ways how we can replicate the CTA with available text elements. It is definitely good to have, but let's not slow down with publishing and interlinking here.

Let's remember, that we can always make another iterations when we have CTA block ready

------

Problem: Almon can't publish articles

@markholdex can you finalize it here (see description) when you have time please?
