### ISSUE TITLE
Problem: unable to add a custom CTA section into an article.

### ISSUE THREAD

**Issue by markholdex** [holdex/holdex-venture-studio#390]
# [Figma design](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/UI-Design?type=design&node-id=690-4798&t=Q3PbiuXQ7j0P8LJw-4)

# Problem
When creating an engaging article, I want to add a CTA section inside, So I can funnel user's attention. 

```[tasklist]
### Solution
- [x] Extend `api/googleconversion` parser to support CTA component
- [x] Extend `renderer` parser to support custom CTA component
- [x] Implement UI component
```

CTA component will be added into the document as table with the following structure.  
<img width="750" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/46079535/a747cf9f-1516-48f0-9f74-61953391b0a1">

Find the JSON that will be fed to the `googleconversion` parser on this link: https://api.npoint.io/a4b1349889fab16c4d4b
`googleconversion` parser output should be something like this: 
```
{
"type": "cta"
"data': {
   "title": "",
   "description: "",
   "link1": null | { "url": "", "text": ""},
   "link2": null | {"url": "", "text": ""}
}
}
```

**Comment by DaoSpirit** [comment]
I will fix this issue.

**Comment by markholdex** [comment]
@DaoSpirit looking forward

**Comment by DaoSpirit** [comment]
I just checked gmail. I will dive into fixing issue.

**Comment by DaoSpirit** [comment]
how can I get access to google drive? @markholdex

**Comment by markholdex** [comment]
@DaoSpirit why do you need access to Google Drive?

**Comment by DaoSpirit** [comment]
it is no needed.
I didn't check whole project. it's clear now.

**Comment by DaoSpirit** [comment]
extend renderer parser to support custom CTA component
 - add case on renderer parser,
 - working hours: 1 hour

**Comment by georgeciubotaru** [comment]
@DaoSpirit Please attach the working PR here.

**Comment by DaoSpirit** [comment]
@markholdex 
Extended api/googleconversion parser to support CTA component.
Extended renderer parser to support custom CTA component

**Comment by DaoSpirit** [comment]
fixed issue @markholdex 
plz check below link.
https://github.com/holdex/holdex-venture-studio/pull/536

**Comment by DaoSpirit** [comment]
I apologize that I didn't adjust pull request title to follow the specification.
I did pull request with supported title.
plz check it. https://github.com/holdex/holdex-venture-studio/pull/537
@markholdex

**Comment by DaoSpirit** [comment]
@georgeciubotaru 
plz share some info of existing cta components.
