### ISSUE TITLE
Power Sunday's Performance Review

### ISSUE THREAD

**Issue by power-f-GOD** [holdex/holdex-venture-studio#401]
### Problems Created (📝):

0. #353
1. #375

### Problems Solved / PR's Merged (✅):

0. #368 --> **(5.0 hrs)**
1. #381 --> **(8.0 hrs)**
2. #395 --> **(3.0 hrs)**
3. #397 --> **(3.0 hrs)**
4. #398 --> **(0.5 hrs)**
5. #400 --> **(0.5 hrs)**

### Problems Pending / PR's Pending (⏳):

  -1. None.

**Comment by power-f-GOD** [comment]
Hi, @zolotokrylin , @power-f-GOD is assigning this issue to you.🙃 Thank you.🙌🏼

Cc: @markholdex

**Comment by zolotokrylin** [comment]
Thank you @power-f-GOD 💪 

Please check your Gmail. I sent you an invitation to join the Chat.

**Comment by zolotokrylin** [comment]
@almon-s the same for you, please join the chat.

**Comment by zolotokrylin** [comment]
Welcome onboard, Power!
