### ISSUE TITLE
Jewelas Performance Review

### ISSUE THREAD

**Issue by jewelas** [holdex/holdex-venture-studio#404]
Hey, it has been a week since I started the trial week. Nice working and discussing with the team. Here is a list of things I did while the trial week.

Discussion on the Problem
#340 

Working PR
#380 

Looking forward to the further process.

**Comment by jewelas** [comment]
Hey @zolotokrylin .
Could you please tell me how to assign this to you?

**Comment by georgeciubotaru** [comment]
Closed with resolution: Inactivity for more than 1 month
