### ISSUE TITLE
Problem: Blockquote doesn't span full width + Link styling isn't applied on `/about` team members

### ISSUE THREAD

**Issue by predrag-us** [holdex/holdex-venture-studio#408]
Problem: Blockquote doesn't span full width + Link styling isn't applied on `/about` team members

Blockquote:
![Image](https://github.com/holdex/holdex-venture-studio/assets/18451941/e4dbca91-0c22-400c-8148-92a2a82b00b4)

Link:
![Image](https://github.com/holdex/holdex-venture-studio/assets/18451941/310deb79-4798-437e-97fb-da35ae9dbd12)

```[tasklist]
### ACs:
- [ ] https://github.com/holdex/holdex-venture-studio/issues/507
- [ ] https://github.com/holdex/holdex-venture-studio/issues/503
```

**Comment by andreisucman** [comment]
Hello. I'll start working on this now.
