### ISSUE TITLE
Problem: wrong `changePercent24Hr` calculation

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/holdex-venture-studio#409]
Problem: something wrong with the `changePercent24Hr` calculation, at least for ETH. A 60% swing didn't happen in the last 24h afaik:
<img width="609" alt="Screenshot 2023-06-19 at 13 44 36" src="https://github.com/holdex/holdex-venture-studio/assets/2462955/1c0761b6-1066-47a5-b20f-241eb49cc4fe">

_Originally posted by @gigor in https://github.com/holdex/holdex-venture-studio/pull/393#discussion_r1233804909_

**Comment by gigor** [comment]
This is data from `https://stage.tools.holdex.io/api/exchange-rate?ticker=ETH`

**Comment by markholdex** [comment]
The value is already in percentage. Meaning `-0.60` is `-0.60%` not 60% price change.
