### ISSUE TITLE
Problem: crypto companies review articles are hard to find

### ISSUE THREAD

**Issue by predrag-us** [holdex/holdex-venture-studio#420]
Problem: Crypto companies' review articles are hard to find. 
Solution: Make it easier to find https://holdex.io/c?filter=review
```[tasklist]
### Tasks
- [ ] https://github.com/holdex/holdex-venture-studio/issues/417
```

**Comment by zolotokrylin** [comment]
Let's give this one a priority please 👍

**Comment by markholdex** [comment]
Updated description link to review articles

**Comment by predrag-us** [comment]
@markholdex 

I find this issue unnecessary since #417 covers all the categories, including this one. Please correct me if I'm wrong.

**Comment by zolotokrylin** [comment]
For now it will be within guides.
Companies needs to be structured into another category, as well as people. So this one is blocked by these issues.

**Comment by predrag-us** [comment]
@zolotokrylin 

So:
For now, companies are a part of Guides. 
But, we're going to move them to a page combining both companies and people.
This is #419. 

As far as I understand, this issue can be closed.
