### ISSUE TITLE
Igor Grechishkin Performance Review

### ISSUE THREAD

**Issue by gigor** [holdex/holdex-venture-studio#423]
Merged single pr https://github.com/holdex/holdex-venture-studio/pull/393.  With code review fixes it took me, around 12hrs spread from Thu, Jun 15 to Tue. 21 Jun.
Issue\non-issue: https://github.com/holdex/holdex-venture-studio/issues/409

**Comment by gigor** [comment]
cc @zolotokrylin

**Comment by gigor** [comment]
@zolotokrylin yeah, I read it and started answering questions. Not gonna finish, I don't have that much extra time.

**Comment by zolotokrylin** [comment]
@gigor for us to know the answers to the questions in the application form is essential to understand if we have a mutual fit. 
My colleague will contact you regarding payment for the trial. The payment will be handled by the end of the month.
