### ISSUE TITLE
Problem: pay for trial to Igor Grechishkin

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/holdex-venture-studio#431]
> for us to know the answers to the questions in the application form is essential to understand if we have a mutual fit. My colleague will contact you regarding payment for the trial. The payment will be handled by the end of the month.

_Originally posted by @zolotokrylin in https://github.com/holdex/holdex-venture-studio/issues/423#issuecomment-1602475763_

**Comment by gigor** [comment]
👋

**Comment by markholdex** [comment]
Hey @gigor we would like to proceed with payment but are lacking your wallet address for USDT. Additionally, we would like to schedule a call with you and discuss our collaboration possibilities. What time feels more comfortable to you? Looking forward!

**Comment by gigor** [comment]
Hey, sure, I'd like to talk! You can check my availability here https://calendly.com/gigorr/30min?month=2023-07

My address 0x566F55a6dfb93878ff2154d71a4a4D952052dAcd (Etherium)

**Comment by markholdex** [comment]
@gigor we have released the payment for your trial period and I scheduled a call with you tomorrow. Talk to you on the call 👋
