### ISSUE TITLE
Problem: can't use top navigation on mobile phone

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/holdex-venture-studio#435]
# Problem statement

I can't navigate back to Home, because logo is not clickable. 

![image](https://github.com/holdex/holdex-venture-studio/assets/1125014/2f38dacd-23f2-42f8-9b16-f73539bfa9e9)

## [Figma Design](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/UI-Design?type=design&node-id=256%3A635&mode=design&t=Nho5OYSfnP89L4er-1)

**Comment by bansalgokul** [comment]
Can you please describe the conditions for this. Because it is working fine for me ?

**Comment by zolotokrylin** [comment]
@bansalgokul iPhone mini, chrome; go to https://holdex.io/about and click on logo in the top nav bar to go back
@predrag-us can you please attach the correct design here

**Comment by predrag-us** [comment]
@zolotokrylin 

This issue is already reported in #405.

**Comment by zolotokrylin** [comment]
@predrag-us ok, but I am not even talking about design here. I am saying that I can't click on the "Home" button.

**Comment by predrag-us** [comment]
@zolotokrylin I'm just stating that if the design was implemented accurately, this wouldn't be a problem.

**Comment by zolotokrylin** [comment]
duplicate of https://github.com/holdex/holdex-venture-studio/issues/405
