### ISSUE TITLE
Problem: We're missing Discord in the `Navigation` and `Footer`

### ISSUE THREAD

**Issue by predrag-us** [holdex/holdex-venture-studio#447]
## [Figma ⏤ `Navigation` Component](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/Holdex?type=design&node-id=3431%3A52392&mode=design&t=zUdnP5nN5ucUWnf8-1)
As you can tell, the Navigation is quite different. Don't mind the new design ⏤ just add Discord.
## [Figma ⏤ `Footer` Component](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/Holdex?type=design&node-id=887%3A11248&mode=design&t=EL9mDNSpoOCopi7h-1)
Added Discord.

**Comment by karenhernandeze** [comment]
Can I be assigned?

**Comment by predrag-us** [comment]
This issue is blocked by #439.

**Comment by predrag-us** [comment]
@karenhernandeze You can assign yourself and work on this issue. 
Please use this invite URL ⏤ https://discord.gg/sEuyYf5euF ⏤ and join yourself, as well.

**Comment by markholdex** [comment]
@MuhammadArslanKhan96 you can proceed with this Problem and let us know your ETA. Thanks 🙏

**Comment by MuhammadArslanKhan96** [comment]
@markholdex sure let me review this

**Comment by MuhammadArslanKhan96** [comment]
@markholdex  Navbar is changed in figma it's in 2 line, and in current version of code its in single line,

so would you please confirm someone else is updating the design of navbar I mean there is any other issue specific for this, or should I update navbar design and add discord link in header footer,

**Comment by predrag-us** [comment]
@MuhammadArslanKhan96 Please read the description ⏤ we just have to add the Discord button in the Navigation and the Footer.

**Comment by MuhammadArslanKhan96** [comment]
@predrag-us oh sorry its my bad, yeah doing that, please assign me this issue

**Comment by MuhammadArslanKhan96** [comment]
@markholdex @predrag-us 
PR created please review it

https://github.com/holdex/holdex-venture-studio/pull/455
