### ISSUE TITLE
Problem: Tweets are stuck in the loading state

### ISSUE THREAD

**Issue by predrag-us** [holdex/holdex-venture-studio#449]
Problem: Tweets are stuck in the loading state. [Here's an example](https://holdex.io/c/case-studies/lumiere-is-now-powered-by-holdex) of where you can see it. 
Solution: Show tweets after they're loaded.

**Comment by surajsharma** [comment]
probably something to do with https://github.com/holdex/holdex-venture-studio/issues/313
