### ISSUE TITLE
Problem: Team members and candidates are not invited to our community

### ISSUE THREAD

**Issue by predrag-us** [holdex/holdex-venture-studio#451]
Join Holdex's community on Discord ⏤ [URL](https://discord.gg/sEuyYf5euF) 

Everyone please join our Discord channel and be part of the community. Click the box once you have joined, thank you!

- [x] @zolotokrylin 
- [x] @markcurchin 
- [x] @georgeciubotaru 
- [ ] @CTAPCKPIM 
- [ ] @Addis-Belete 
- [x] @surajsharma 
- [ ] @power-f-GOD 
- [x] @VarinderClearpool 
- [x] @kfujita0520 
- [ ] @Hybris17 
- [x] @accompany1205

**Comment by almon-s** [comment]
@markcurchin could you update our airtable entry emails with a discord link too, thanks. It should just be an additional sentence

**Comment by markholdex** [comment]
I did update our entry email. Also closing this issue because the plan is not to move everyone from the team in Discord yet. So we'll invite gradually.
