### ISSUE TITLE
Muhammad Arslan Performance Review

### ISSUE THREAD

**Issue by MuhammadArslanKhan96** [holdex/holdex-venture-studio#454]
Hey @zolotokrylin , it has been a week since I started a trial week, 

PR worked on: 
https://github.com/holdex/holdex-venture-studio/pull/453
https://github.com/holdex/holdex-venture-studio/pull/455
https://github.com/holdex/holdex-venture-studio/pull/469

Issues
https://github.com/holdex/holdex-venture-studio/issues/370
https://github.com/holdex/holdex-venture-studio/issues/412

Discussion:
https://github.com/holdex/holdex-venture-studio/issues/372
https://github.com/holdex/holdex-venture-studio/issues/412

No of hours spent:
60

**Comment by zolotokrylin** [comment]
@MuhammadArslanKhan96 are you open to finish the whole problem? Now you have just the front-end without integration with the backend.

**Comment by MuhammadArslanKhan96** [comment]
@zolotokrylin above issues are fixed and pushed in same PR

**Comment by georgeciubotaru** [comment]
@MuhammadArslanKhan96 Please finish with the PRs mentioned in the description (they should be merged), so we can review your performance. Thank you!

**Comment by zolotokrylin** [comment]
log: the candidate is not active
