### ISSUE TITLE
Problem: Twitter logo changed

### ISSUE THREAD

**Issue by MuhammadArslanKhan96** [holdex/holdex-venture-studio#473]
# Problem statement

- As we all know Twitter logo is changed but we are still using the previous one.

# Proposed solution

- We can update simply twitter logo

### ETA

- 20 minutes for dev

**Comment by wassaven** [comment]
@zolotokrylin 
Trial PR from Wassaven
https://github.com/holdex/holdex-venture-studio/pull/525
