### ISSUE TITLE
Kevin Forster Performance Review

### ISSUE THREAD

**Issue by winter-sols** [holdex/holdex-venture-studio#482]
@zolotokrylin @markcurchin @georgeciubotaru  , it has been 2 week since I started a trial.

- PRs worked on:
https://github.com/holdex/holdex-venture-studio/pull/464
https://github.com/holdex/holdex-venture-studio/pull/466

- Issues
https://github.com/holdex/holdex-venture-studio/issues/446
https://github.com/holdex/holdex-venture-studio/issues/458
https://github.com/holdex/holdex-venture-studio/issues/459
(459: Verified all the features are good.)
https://github.com/holdex/holdex-venture-studio/issues/405
(405: Closed when 446 closed because of similar conent)
- Hours spent:
60

- PS: I am also open to smart contract work. Please let me know if any updates. Thank you

**Comment by winter-sols** [comment]
@zolotokrylin @markcurchin @georgeciubotaru 
Could you check it?

**Comment by georgeciubotaru** [comment]
@winter-sols Thank you for your report. I will check and let you know.

**Comment by georgeciubotaru** [comment]
Hi, @winter-sols.

Kevin made a good job, he proved that he is interested in working with us. He was able to identify problems, solve existing issues and use our working guides. However, he doesn't apply high skills in taking the lead for the PRs he resolves.

- code quality wasn't high
- delayed delivery for PRs (more than 4hrs)
- UI QA wasn't accurate

I may suggest taking the final task as proof that he can handle complex tasks (knows how to structure the work and deliver the code).

https://github.com/holdex/holdex-venture-studio/issues/5

Notes: Our mantras are
- Deliver high-quality code
- Be transparent

@zolotokrylin, @markcurchin  FYI

**Comment by winter-sols** [comment]
@georgeciubotaru Thank you for your update.
I will try my best to fix the issue #5

**Comment by winter-sols** [comment]
@zolotokrylin  @markcurchin @georgeciubotaru Hi, how are you?
I already made my mind not to work with you.
Can you pay for the work in the trial period?

**Comment by zolotokrylin** [comment]
Yes, we will make a payout.
@georgeciubotaru please define a fair amount for this trial task based on the value delivered and the complexity of the issues.

**Comment by georgeciubotaru** [comment]
@zolotokrylin Sure.
@winter-sols In the meantime, please provide your ERC-20 wallet. (the payment will be settled by the end of the month)

**Comment by winter-sols** [comment]
@zolotokrylin Sure

**Comment by winter-sols** [comment]
@zolotokrylin @georgeciubotaru 
Can I get paid today?

**Comment by georgeciubotaru** [comment]
Hey @winter-sols please provide your ERC-20 wallet

**Comment by winter-sols** [comment]
0x95385fb5c43e1022847adaf66f4fcc131b85ac2c

**Comment by georgeciubotaru** [comment]
@markcurchin Please initiate the transaction, for the above address and let us know when it's ready

**Comment by winter-sols** [comment]
@markcurchin @georgeciubotaru @zolotokrylin 
When can I expect the payment?

**Comment by markholdex** [comment]
@winter-sols payment has been released. I saw activity on BEP-20 so I released on that network.
