### ISSUE TITLE
Problem: Price charts in Holdex website is not loading

### ISSUE THREAD

**Issue by almon-s** [holdex/holdex-venture-studio#486]
It is not loading for me. If an existing issue exists already please close this.

<img width="1512" alt="Screenshot 2023-08-03 at 3 34 38 PM" src="https://github.com/holdex/holdex-venture-studio/assets/112711034/8c56aced-8381-45e9-83da-414ef6c2b229">

<img width="1512" alt="Screenshot 2023-08-03 at 4 33 05 PM" src="https://github.com/holdex/holdex-venture-studio/assets/112711034/02bb4aff-9f41-4fb1-b299-83ea928cf018">

**Comment by surajsharma** [comment]
this is likely due coingecko screwing up their api permissions, investigating...

**Comment by surajsharma** [comment]
log: i do not find a chart in the incoming data `message` in local dev, strange..

**Comment by almon-s** [comment]
@surajsharma could we fix this quickly? if not is it possible to temporarily hide the chart? We cant be displaying a broken chart on our live website

**Comment by surajsharma** [comment]
@almon-s i'm on it

**Comment by georgeciubotaru** [comment]
@surajsharma Please focus on your high-priority issues

**Comment by georgeciubotaru** [comment]
![image](https://github.com/holdex/holdex-venture-studio/assets/8217518/c874bbc9-e814-4d18-81ae-888e55e96fd2)

**Comment by surajsharma** [comment]
> ![image](https://user-images.githubusercontent.com/8217518/258083606-c874bbc9-e814-4d18-81ae-888e55e96fd2.png)


yeah they jusut went paid

**Comment by almon-s** [comment]
> ![image](https://user-images.githubusercontent.com/8217518/258083606-c874bbc9-e814-4d18-81ae-888e55e96fd2.png)

@zolotokrylin FYI

**Comment by georgeciubotaru** [comment]
@almon-s Please check now and feel free to close the issue if it's resolved

**Comment by surajsharma** [comment]
working for me
