### ISSUE TITLE
Problem: Service button is missing from the navigation bar 

### ISSUE THREAD

**Issue by almon-s** [holdex/holdex-venture-studio#488]
We should have a Service button on the navigation bar for easy customer access. Currently, they have to read through the Home or About page and find the service link in the middle.

**Comment by predrag-us** [comment]
Services added to the Navigation ⏤ design in the description.

**Comment by georgeciubotaru** [comment]
@zolotokrylin, @markcurchin 1 thing here

Do we need to transform the `Services` thread into a page like `About`?

**Comment by zolotokrylin** [comment]
@georgeciubotaru No need. No additional value I can see of doing this. But I can see the cost.

**Comment by georgeciubotaru** [comment]
@predrag-us, @almon-s  Can you handle this? It's a 5-10 minute change

**Comment by almon-s** [comment]
@georgeciubotaru yes i can do it but i agree with Vadim if there's cost. Main purpose here was to have a dedicated button that directs to our existing services article/page easily

**Comment by almon-s** [comment]
@zolotokrylin I can see the direction of such companies from your links, the focus seems to be on portfolio companies and not necessarily the services. However, we still need to find a way to showcase our service offerings or atleast somehow show what we can do in a way that the clients can see it easily.

So maybe not a dedicated service button but atleast have a link to our service thread from our portfolio page? Cause the main problem was that clients would have to read through about to find what we offer (not easily accesible).

But I believe we could use our portfolio page then. Have a flavour text that links to services so this way clients can see our deicated portfolio and also be able to access what other services we do provide? I think this could do

**Comment by zolotokrylin** [comment]
@almon-s sounds good. All of these pages should lead to services: Portfolio, About Us, and For Startups pages.

**Comment by predrag-us** [comment]
Removed Services from the Navigation.

**Comment by almon-s** [comment]
@zolotokrylin seems for Portfolio the header is actually a part of the code. I can either change that and add a line that links to Services. Or, i dont know an alternative since Portfolio doesnt have an article doc it seems.

**Comment by zolotokrylin** [comment]
Log: it was discussed and resolved, that no code changes are needed here and that all main pages should have a reference to the Services article via our documents interlinking.
