### ISSUE TITLE
Problem: current desktop navigation menu has decreased user navigation rate

### ISSUE THREAD

**Issue by markholdex** [holdex/holdex-venture-studio#493]
# Problem statement

- [ ] The placement of the navigation items on the second row has decreased user navigation rate
- [ ] Hiding the navigation elements has decreased user navigation rate. 

Because the links are not always displayed, the users are not encouraged to navigate between the pages. Therefore the rate has decreased by 50% according to our analytics. 

# Proposed solution

- [x] Rethink desktop navigation UX/UI
- [ ] Implemented new desktop navigation

--- 

### [Figma Design](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/Holdex?type=design&node-id=396%3A2729&mode=design&t=HPm8519rrC0Jj5t0-1)

**Comment by markholdex** [comment]
@predrag-us have a look at this issue and please proceed if you are available. Let us know the ETA for the solution. Thanks!

**Comment by predrag-us** [comment]
I'm unsure about the ETA since I don't have a solution in sight. Hopefully, I'll have the proposal today. ETA: 6h.

**Comment by zolotokrylin** [comment]
@markholdex @predrag-us don't overthink here please (don't waste the resources).
For the desktop, please revert to the navigation we had before: all items in one line.

**Comment by zolotokrylin** [comment]
That's the soluction.

**Comment by predrag-us** [comment]
@zolotokrylin That's exactly what I did, with minor updates so it can work on all breakpoints. I'll move the issue to Ready shortly.

**Comment by predrag-us** [comment]
Log: Assigned myself again to sync all pages with the new (old) design.
