### ISSUE TITLE
Problem: can't add customers testimonial to our portfolio articles

### ISSUE THREAD

**Issue by markholdex** [holdex/holdex-venture-studio#494]
# Problem statement

- [x] Customers have provided testimonials about our partnership success. We can add them in the article as a quote however it feels visually disconnected from the information about the person who left the testimonial. (name, title and company)

# Proposed solution

- [x] Design separate testimonial component that will stand out from the rest of the content
- [x] Parse article content for testimonial component
- [x] Implement testimonial component design

--- 

# [Figma Design](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/Holdex?type=design&node-id=4812%3A75645&mode=design&t=HPm8519rrC0Jj5t0-1)

##  [Test article available on localhost](https://stage.holdex.io/c/announcements/article-components)

To view this article on your local machine, change the parameters following this [comment instruction](https://github.com/holdex/holdex-venture-studio/issues/340#issuecomment-1591638091).

**Comment by markholdex** [comment]
@predrag-us have a look into this problem statement. Let me know if you have any questions. Don't forget to leave the ETA Thanks!

**Comment by predrag-us** [comment]
ETA: 3 hours.

**Comment by predrag-us** [comment]
@markholdex Please have a look at the design and let me know if we need something more distinguishing or if we're good with this variation. Thank you!

**Comment by predrag-us** [comment]
@markholdex Please check the comment above. Thanks!

**Comment by zolotokrylin** [comment]
@predrag-us how would it look inside the article, please?

**Comment by predrag-us** [comment]
@zolotokrylin Sure, [here you go](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/Holdex?type=design&node-id=4906%3A34738&mode=design&t=5Wqzo171BbWD6D7h-1).

**Comment by markholdex** [comment]
@predrag-us looks good. Left a minor comment to try things out. Maybe you can do it as a copy to compare and we'll pick the one. Thanks!

**Comment by predrag-us** [comment]
@markholdex I've answered your comments, please have a look. Thanks!

**Comment by Isaacprogi** [comment]
lkzzzzzzzzzzzzzzzzzzzzzzn
lkzzzzzzzzzzzzzzzzzzzzzzn

**Comment by misagfo** [comment]
Hi Mark, I don't understand where the testimonial component should be displayed, you can make a screenshot on the site
tell me in more detail what to do

**Comment by markholdex** [comment]
@misagfo testimonial component should not be displayed in a specific place. It's dynamic. We want it to be displayed anywhere in our articles (where we need of course). 

I updated the task description. You will find the test article where the current testimonial component is located. What you need to do is to transform that component (table) into the testimonial component we see in Figma design. All within the current codebase and practices. 

Let me know if you still have questions.

**Comment by misagfo** [comment]
![image](https://github.com/holdex/holdex-venture-studio/assets/21268553/f6ff9600-d7a4-41cb-88aa-061734871c2e)

I understood correctly, I have to change this table with this

![image](https://github.com/holdex/holdex-venture-studio/assets/21268553/85e589dc-81d3-42e2-b159-5f731fffce5f)

**Comment by markholdex** [comment]
@misagfo let me know if you started working on this Problem.

**Comment by misagfo** [comment]
> @misagfo let me know if you started working on this Problem.

I started yesterday, analyzing the code, there are many files and I can't find where the imported table is in this URL http://127.0.0.1:3000/c/announcements/article-components

**Comment by markholdex** [comment]
@misagfo can you please attach a PR to indicate that you have started on this Problem. 

>analyzing the code, there are many files and I can't find where the imported table is in this URL http://127.0.0.1:3000/c/announcements/article-components

I didn't get it. What is your question here?

**Comment by misagfo** [comment]
I don't understand anything in the .pug files
I found the table component but I don't understand how it appears in the url c/announcements/article-components I mean in the .pug files

Well, I can make a component with Testimonial, but I don't know how to display it in this URL c/announcements/article-components by printing all these .pug files

**Comment by markholdex** [comment]
@misagfo I can give you more context but you will also need to look for it yourself in the repository. 

The cycle is as follows:

1. We have a Google Doc file where we edit the content and create the table
2. Using the plugin we developed, we transform the Google Doc into a JSON file that is stored on our back-end
3. When a page is loaded, the front-end application makes request to our back-end. 
4. As a response, the app receives the JSON, parses it, and transforms various JSON elements into content. All elements are rendered together on the website page using our Rendering engine. If any of the elements are matched with a component from our components library, it will automatically be used and populated with the content.  

So, the process is basically parsing these elements and rendering them as demanded by the article content.

**Comment by misagfo** [comment]
good

in which place to find this

**Comment by markholdex** [comment]
@misagfo in the current repository as mentioned in other messages earlier.

**Comment by misagfo** [comment]
> I can give you more context but you will also need to look for it yourself in the repository.
> 
> The cycle is as follows:
> 
> 1. We have a Google Doc file where we edit the content and create the table
> 2. Using the plugin we developed, we transform the Google Doc into a JSON file that is stored on our back-end
> 3. When a page is loaded, the front-end application makes request to our back-end.
> 4. As a response, the app receives the JSON, parses it, and transforms various JSON elements into content. All elements are rendered together on the website page using our Rendering engine. If any of the elements are matched with a component from our components library, it will automatically be used and populated with the content.
> 
> So, the process is basically parsing these elements and rendering them as demanded by the article content.

OK I understood the idea, now I see if I can find the component for this JSON )), if you have any idea what the component is, please suggest me

**Comment by markholdex** [comment]
@misagfo Sorry but no more clues. We need to assess your abilities to figure things out within an unfamiliar environment.

**Comment by misagfo** [comment]
Hi Mark, how can I add the style property in Google docs

**Comment by misagfo** [comment]
> Hey @misagfo, sorry I don't understand. Can you please ask it as a question?

there in google docs the style property is missing, the property must be added for the component to work

**Comment by markholdex** [comment]
@misagfo You do what you believe you need to do in order to solve the problem. You can address questions but I will not answer you with step-by-step instructions. I will also not answer to approve or reject any of your ideas. I can only give you high-level directions. 

Right now, I don't understand what are you expecting from me with your previous message. I expect you to ping me in your PR when your solution is ready and tested.

**Comment by misagfo** [comment]
to work the specific component must be added here  "style": "unordered" HERE ->
![image](https://github.com/holdex/holdex-venture-studio/assets/21268553/99f67ce3-4df0-431c-82f0-c1d58e7bed56)

I don't have access to add this property "style": "unordered" in google docs, I can't solve the problem without access to JSON Google Docs

**Comment by markholdex** [comment]
@misagfo I'm afraid you didn't research the project enough. You already have access to the JSON of the Google Docs and it's not the code snippet you are showing above. The code snippet from above is just the content of the document.

**Comment by misagfo** [comment]
yes, I only have access to see it, I don't have the right to edit, the Edit button is blocked

well, I'll analyze a little later, maybe I don't understand something

**Comment by blueogin** [comment]
@markholdex
I referenced this https://github.com/holdex/holdex-venture-studio/issues/340#issuecomment-1591638091 to see the testimonial component but it seems that the codebase is changed a lot and it does not work

**Comment by markholdex** [comment]
> @markholdex I referenced this [#340 (comment)](https://github.com/holdex/holdex-venture-studio/issues/340#issuecomment-1591638091) to see the testimonial component but it seems that the codebase is changed a lot and it does not work

@blueogin the comment you are referencing are instructing on how to launch the project on localhost. (just the additional settings required). You won't find the testimonial component there. In fact, we don't have any testimonial component yet. However, you can try and run the test article from the description on your localhost. Over there, you will find the testimonial section.

**Comment by blueogin** [comment]
I understood that I can see the testimonial section like below on my local com by changing the configuration with the comment I mentioned.
![image](https://github.com/holdex/holdex-venture-studio/assets/43612769/8f1199c0-46dd-42b4-9d94-7f89e6d46905)
The key is that I can not follow the comment I mentioned because the codebase is different from the code indicated
Current codebase looks like this
![image](https://github.com/holdex/holdex-venture-studio/assets/43612769/6b85399a-af79-4afa-af48-bc56731ed0e1)

To talk to you about my understanding, firstly, I should implement testimonial component as fits in figma design, and parse the content of testimonial(I guess it will be provided in json form) and inject to the component

**Comment by blueogin** [comment]
I think if you provide any mock data, or any api that provides the data which involves testimonial content, there is no problem though

**Comment by markholdex** [comment]
@blueogin mock data is not necessary because the API already returns the information. As long as you can run the app locally and change the environment, the API will return it. 

@georgeciubotaru did we change anything related to how we switch to stage/local API?

**Comment by georgeciubotaru** [comment]
@blueogin First of all, What are you trying to do?

Secondly, by default on localhost, is connected to the `stage` API.
To switch to the `prod` API you need to update the line `55`.

**Comment by blueogin** [comment]
I hope API works but it does not
![image](https://github.com/holdex/holdex-venture-studio/assets/43612769/7aaa4b1c-06a8-40ca-a23e-98f17707bd5b)
![image](https://github.com/holdex/holdex-venture-studio/assets/43612769/8cd38bc8-e666-4e5a-97c6-795440b379d2)

**Comment by georgeciubotaru** [comment]
@blueogin What URL are you trying to access?

**Comment by blueogin** [comment]
http://localhost:3000/
![image](https://github.com/holdex/holdex-venture-studio/assets/43612769/742f3909-a703-44c5-8c3f-fa59b4706b9d)

**Comment by georgeciubotaru** [comment]
@blueogin Why do you need the `main` route in production? This is a custom route and cannot be accessed from the local environment. You have the `test` article to check for `testimonials` blocks. No need to switch to production API

**Comment by markholdex** [comment]
`c/announcements/article-components` is the route you should try to access from localhost

**Comment by blueogin** [comment]
I see @georgeciubotaru
I want this, because I do not know the data form of the testimonial component
I should know this to parse data to inject in testimonial component
This is the reason why I asked mock data
I guess it should looks like this, but need to confirm

> {
type: 'testimonial',
picture: 'https://google.com/',
name: 'John',
title: 'Great!',
content: 'Hi! Nice to meet you',
},

**Comment by blueogin** [comment]
I can not see any from this URL
http://localhost:3000/c/announcements/article-components
Or is it wrong? please inform me the correct link
![image](https://github.com/holdex/holdex-venture-studio/assets/43612769/19025da3-748e-4acd-9080-7f43635f3dff)

**Comment by blueogin** [comment]
It works
Nevermind

**Comment by blueogin** [comment]
https://github.com/holdex/holdex-venture-studio/pull/570
Opened draft PR
I am working on testimonial data parser

**Comment by zolotokrylin** [comment]
<img width="931" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/46079535/bc3ffc26-e8cc-4d72-bc83-1ab691f9e166">

**Comment by zolotokrylin** [comment]
Before closing any new Problem, make sure it is resolved. 
There is no point in closing the issue, and right away reporting a bug in a separate issue.
