### ISSUE TITLE
Problem: Button component is not following Figma design

### ISSUE THREAD

**Issue by georgeciubotaru** [holdex/holdex-venture-studio#544]
I have the assumption that button styles are not by design.
- Border color
- Background color in (hover|focus) states

**Comment by georgeciubotaru** [comment]
@angelicawill Can you please help here?

Just go through the Button styles and compare them with the designs.

**Comment by zolotokrylin** [comment]
@georgeciubotaru where does this problem derive from? Which issue?

**Comment by georgeciubotaru** [comment]
@zolotokrylin During the review of #537, I saw that button styles in light mode are wrong
