### ISSUE TITLE
Problem: Jobs category article doesn't have a default OG image

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/holdex-venture-studio#571]
# Problem: Jobs category article's title tag is not complete

Current value: `articleTitle`
Proper value: `articleTitle` - Job | Holdex

# Problem: Jobs category posts doesn't have a default OG image

Post example: 
- https://twitter.com/HoldexIo/status/1745998045077278817
- same in LinkedIn

<img width="634" alt="image" src="https://github.com/holdex/partners/assets/1125014/a6735886-00a6-4ec6-8eea-a45e2d4ca958">
<img width="580" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/1125014/3376ff2f-5a4d-4ec5-ba00-0f44ed4f9296">

_Originally posted by @zolotokrylin in https://github.com/holdex/partners/issues/21#issuecomment-1890264655_

**Comment by neverm25** [comment]
## In the first problem, should I add the ` - Job | Holdex` to the link preview or your website?
![Screen Shot 2024-01-24 at 9 38 46 PM](https://github.com/holdex/holdex-venture-studio/assets/138539187/4832d056-e5ec-4663-9ee2-3646df092037)
![image](https://github.com/holdex/holdex-venture-studio/assets/138539187/51931d6e-db6c-4ca2-997e-f0b44fe4cde2)


## In the second problem, should I show the logo icon on here?
![Screen Shot 2024-01-24 at 9 15 24 PM](https://github.com/holdex/holdex-venture-studio/assets/138539187/92ffca69-58a1-4296-9dfb-314e4f29360b)

**Comment by markholdex** [comment]
@neverm25 Since the Problems are only related to OG tags, we should only address them. 

1. This means the first problem should only be related to the articles from our `/jobs` category as you pointed out in your screenshot. 
1. I'll give you a small clue here. We have a `default OG image` that should be displayed in case the article doesn't have one. Something is wrong with it here (or maybe in other places too)

**Comment by neverm25** [comment]
I was going to push my updated code.
But I don't have the permission to write.

![image](https://github.com/holdex/holdex-venture-studio/assets/138539187/7bb54500-5140-4a65-9cc5-0aa8d05dbf04)

**Comment by markholdex** [comment]
<img width="864" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/46079535/2de1a170-dbe8-49b6-b3be-192e90b064f3">
