### ISSUE TITLE
Problem: users can't view Apply links on job position pages

### ISSUE THREAD

**Issue by markholdex** [holdex/holdex-venture-studio#581]
# Problem statement

- Whenever I try to add parameters to the link of the application form in any of the job posts it makes the button `Apply` to disappear. 
- Adding parameters to an application link like this  `https://apply.holdex.io/job?source=holdex.io` and inserting the link into the website does not render the link at all.

**Comment by zolotokrylin** [comment]
@markholdex do you remember we discussed, that we will just replace APPLY with Go To Action block. And it will open a form in a new Tab.

Let's me know if something is not clear.

**Comment by markholdex** [comment]
@zolotokrylin CTA I remember but new page not. I guess we can agree on it.
