### ISSUE TITLE
Problem: users can't see CTA section

### ISSUE THREAD

**Issue by markholdex** [holdex/holdex-venture-studio#583]
## Problem
In #537 we introduced a new component called CTA. Now the CTA component is not being rendered correctly. It is available in one of our articles here: https://holdex.io/c/jobs/developer-advocate

<img width="902" alt="Screenshot 2024-02-08 at 10 50 11" src="https://github.com/holdex/holdex-venture-studio/assets/46079535/3b08b8c4-08d0-42a3-8a2b-be9faf165af7">

**Comment by georgeciubotaru** [comment]
@uluksamakov You can check first if our conversion works as intended:

Endpoint: `/api/google-conversion`
JSON payload: https://api.npoint.io/e7fb775c6269ede3b94a

@markholdex FYI
