### ISSUE TITLE
Problem: twitter tweets has disappeared from threads

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/holdex-venture-studio#60]
Component Design: [URL](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/UI-Design?node-id=605%3A8613&t=vkNfYGgIuE2Zs31p-1)

Existing example component: https://github.com/holdex/twitter-widget

Scope

- [x] Add Twitter component in this repo and render items from the thread body
- [x] Update the component according to the designs

**Comment by georgeciubotaru** [comment]
@surajsharma This was your Problem, and it's resolved. See my comments. I've provided you new task
