### ISSUE TITLE
Problem: new Hero Section design not implemented

### ISSUE THREAD

**Issue by matthewvogas** [holdex/holdex-venture-studio#625]
# Problem

 The landing page design is complete, but the hero section, which is crucial for capturing users' attention, has not been implemented yet. The hero section will introduce the product and set the tone for the rest of the page.

### Job story
When a user visits the landing page, I want to grab their attention immediately with a visually striking and informative hero section, so I can encourage them to explore further or take action.

# Proposed solution
Implement the hero section using the provided Figma design, focusing on responsive layout, typography, dark-light mode and a call-to-action button (portfolio).

Figma hero section: https://www.figma.com/design/ouzfjob16mSlDSCY7MT9ZM/Holdex-(https%3A%2F%2Fgithub.com%2Fholdex%2Fmarketing%2Fissues%2F68)?node-id=9032-65462&t=QiQWYYTDBhOLzaZ7-4

### ETA

Estimated: 4h

**Comment by zolotokrylin** [comment]
@matthewvogas @markcurchin let's wrap up the relevant PR and close this problem, please 🙏

**Comment by matthewvogas** [comment]
I'm on my way!

**Comment by zolotokrylin** [comment]
How did we get this merged? 

<img width="612" alt="image" src="https://github.com/user-attachments/assets/0430ad39-780a-4fcd-bf60-514085f4677d">

**Comment by matthewvogas** [comment]
> How did we get this merged?
> 
> <img alt="image" width="612" src="https://private-user-images.githubusercontent.com/1125014/373076524-0430ad39-780a-4fcd-bf60-514085f4677d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MjMxMDYsIm5iZiI6MTcyNzkyMjgwNiwicGF0aCI6Ii8xMTI1MDE0LzM3MzA3NjUyNC0wNDMwYWQzOS03ODBhLTRmY2QtYmY2MC01MTQwODVmNDY3N2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMDIzMzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBlNjY1ODViNDNiYjhlOTlhMTg4MDc2NDg4NjEwYWRlZTkwZGRhMDc3NWQwNzA4N2YwZTQyY2ZlZGJjZjFkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.z1LZaojo6t0ktUlIOghdnYZPMBV7Ex3yCycTMserFO8">

I just checked all the available phones in the image, and it only looks like this for Surface Duo iPad, anyway I will solve it in another PR

![image](https://github.com/user-attachments/assets/263cdaaa-b1c0-4a62-858e-202fcbfacb6e)
