### ISSUE TITLE
Trial: Teodorus Nathaniel

### ISSUE THREAD

**Issue by markholdex** [holdex/holdex-venture-studio#638]
sub of: 
- https://github.com/holdex/hr/issues/597

**Comment by markholdex** [comment]
Hey @teodorus-nathaniel thanks for accepting our trial. I have prepared the following Goal for you: 

- https://github.com/holdex/pr-time-tracker/issues/283

Let me know in the goal when you begin working on it and what is the ETA for completion.

I strongly recommend to check and follow our contribution guidelines: 
- https://github.com/holdex/developers/blob/main/.github/CONTRIBUTING.md

Not following them could result in failed / cancelled trial task

**Comment by markholdex** [comment]
Feel free to ask any process or organizational questions about the trial here.

**Comment by teodorus-nathaniel** [comment]
Hi @markholdex! I’ve started setting up the repo and analyzing the project goals. I’ll post an ETA update in the goal thread soon.

**Comment by markholdex** [comment]
Hey @teodorus-nathaniel did you join our Discord already? 

If not, here's the link. Let's get in touch.
https://discord.gg/cHxnURgGgk

**Comment by teodorus-nathaniel** [comment]
Yes, I'm already in, my discord is Dynatle 🤝

**Comment by markholdex** [comment]
log: closing this issue since the trial objective has been completed. Will continue the discussion in Discord.
