### ISSUE TITLE
Trial: Fikri Albaihaqi

### ISSUE THREAD

**Issue by markholdex** [holdex/holdex-venture-studio#644]
sub of: 
- https://github.com/holdex/hr/issues/593

**Comment by markholdex** [comment]
Hey @fikri-albaihaqi let's use this issue to track your progress on trial. I canceled your previous Goal since you mentioned your strong side is coding. 

I will assign you to a coding goal soon.

**Comment by fikri-albaihaqi** [comment]
Hey @markholdex I decided not to continue my trial with Holdex. I appreciate your time and consideration and thank you for the opportunity!

**Comment by zolotokrylin** [comment]
Good luck @fikri-albaihaqi!
