### ISSUE TITLE
Problem: redirect conflics

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/holdex-venture-studio#87]
Try to go to this page https://holdex.io/c/companies/pickle-finance:
a. via direct URL input
b. via link on this page https://holdex.io/portfolio

_Originally posted by @zolotokrylin in https://github.com/holdex/holdex-venture-studio/issues/85#issuecomment-1512808784_

**Comment by winter-sols** [comment]
@zolotokrylin, @georgeciubotaru , @markholdex 
We can't reproduce this issue on local server. 
We can this only on deployed server.

**Comment by winter-sols** [comment]
Could you show me the command we use to build & deploy to vercel?
This is server side redirection issue.

**Comment by winter-sols** [comment]
To resolve this issue, we need to add .htaccess and .redirect file.

**Comment by georgeciubotaru** [comment]
@winter-sols We are using Vercel for redirect, therefore `Vercel` config is the only place for updating these values
